apiVersion: v1
kind: Namespace
metadata:
  name: telegram-bot
  labels:
    name: telegram-bot
    env: production
---
apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
  namespace: telegram-bot
type: Opaque
stringData:
  telegram-token: "${TELEGRAM_TOKEN}"
  anthropic-api-key: "${ANTHROPIC_API_KEY}"
  mongo-root-password: "${MONGO_PASSWORD}"
  mongo-user: "${MONGO_USER}"
  sentry-dsn: "${SENTRY_DSN}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
  namespace: telegram-bot
data:
  BOT_NAME: "Sophie"
  BOT_PERSONALITY: "You are Sophie, a friendly and helpful assistant."
  MESSAGE_HISTORY_LIMIT: "10"
  SPEECH_SPEED: "1.3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: telegram-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: telegram-bot
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: mongo-root-password
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: telegram-bot
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: telegram-bot
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
        - name: telegram-bot
          image: iklob1/telegram-bot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: telegram-token
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: anthropic-api-key
            - name: MONGODB_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongodb:27017/telegram_bot?authSource=admin"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: mongo-root-password
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: sentry-dsn
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: telegram-bot
  namespace: telegram-bot
spec:
  selector:
    app: telegram-bot
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: telegram-bot-hpa
  namespace: telegram-bot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telegram-bot
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

